### ISSUE TITLE
Add some examples of restart scripts

### ISSUE THREAD

**Issue by bboreham** [weaveworks/guides#10]
The current guides assume you are working interactively.  It would be good to give one or two examples where you wish to start weave on machine boot, e.g. via `systemd` or `upstart`.

This should include where to set `DOCKER_HOST`

**Comment by errordeveloper** [comment]
Sure, I've been wanting to do that for a while, but now I cannot think of this without thinking about persisting peer addresses as part of that, as IPAM requires it to somehow happen when user decides to grow their cluster, which makes the task quite a bit more interesting too.

**Comment by errordeveloper** [comment]
Implementation-wise, we could even ship a helper container that writes peers file in a certain format, it can have some path bind-mounted to write into, e.g. `/etc/weave/`. In fact, there is a common file format that will work for systemd, upstart and the classic type of init daemon. The format is essentially the variable declaration syntax in Bourne shell, I have just double-checked and all 3 of the above are capable of parsing that.
