### ISSUE TITLE
guides/weave-and-docker-platform/README.md... how does this handle reverse proxying?

### ISSUE THREAD

**Issue by faddat** [weaveworks/guides#110]
Hey guys,

Right now we use a wildcard + traefik to handle our reverse proxying.  Since that doesn't support TCP, we're looking at other solutions.  Basically our use case is:

1) Our customer launches an application
2) Container(s) are launched, and they're named $USERNAME-RANDOMSTRING-$APPNAME = *
3) Traefik is connected to marathon, so it routes *.klouds.org to the appropriate endpoint(s)

Can we coax the same functionality out of weave?  It would surely be lighter....

Thanks!

-Jake

**Comment by errordeveloper** [comment]
@faddat that's a very interesting question! Would you mind closing this issue and posting to [the mailing list](https://groups.google.com/a/weave.works/forum/#!forum/weave-users)?

**Comment by faddat** [comment]
Don't mind at all.
