### ISSUE TITLE
"Getting Started" vs "Creating Distributed Apps" with Weave & Docker confusion

### ISSUE THREAD

**Issue by rade** [weaveworks/guides#120]
It's not at all clear what the difference is. Curiously the latter comes before the former in the side bar. And "Getting Started" _does_ involve running things on multiple machines.

**Comment by abuehrle** [comment]
@rade I agree with you.  It was what the original doc was called and I just kept the title.  Let me know what a better overall title would be.  The 3 part tutorial has little to do with 'creating distributed apps', perhaps, 'Connecting Docker Containers with Weave?'

I am totally open to re-arranging how the guides are grouped in the side bar.

**Comment by abuehrle** [comment]
Changed this title to: 'Connecting Docker Containers With Weave" and made it clear that's a 3 part tutorial.
