### ISSUE TITLE
Upgrade Docker in ECS AMI

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/guides#129]
It's using 1.7.1, which exhibits https://github.com/docker/docker/issues/14738

**Comment by 2opremio** [comment]
@errordeveloper Our AMI provides whatever the base ECS image provides. It's up to Amazon to fix this stuff.

**Comment by 2opremio** [comment]
@errordeveloper Also, please report this kind of issues in the weaveworks/integrations repository.

**Comment by errordeveloper** [comment]
Ah, ok.
