### ISSUE TITLE
Mesos guide: App stuck in "Deploying"

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/guides#145]
When following the  Mesos guide: http://weave.works/guides/platform/mesos-marathon/os/centos/cloud/vagrant/ ...

... the App gets stuck in Deploying state for hours:

<img width="1279" alt="screen shot 2015-12-15 at 1 57 58 pm" src="https://cloud.githubusercontent.com/assets/2362916/11812457/e7c2e67e-a333-11e5-8523-db82f58371a5.png">

The debugging information shows an `Abnormal executor termination`. I don't know enough about Mesos to debug it further:

<img width="1259" alt="screen shot 2015-12-15 at 1 59 00 pm" src="https://cloud.githubusercontent.com/assets/2362916/11812488/19e05524-a334-11e5-968c-55fe7360bf53.png">

**Comment by errordeveloper** [comment]
I have recently updated this to use latests versions of all the things (#197). This is generally a usual thing with Mesos/Marathon, and I believe this is an artefact of how it pulls images. Usually, it succeeds eventually.
