### ISSUE TITLE
Nit-picking wording

### ISSUE THREAD

**Issue by bboreham** [weaveworks/guides#146]
From http://weave.works/guides/weave-docker-centos-simple.html:

> downloaded a docker image containing all three Weave components: Weave Router, WeaveDNS, and the Weave Docker API Proxy

Currently those components are in two images, and as of Weave Net 1.4 you would have downloaded a third image containing the plugin.

**Comment by abuehrle** [comment]
thnks @bryan 

fixed: 6eba2ef7b61aa1dcdbee3ea9a438454aab6480bd
