### ISSUE TITLE
Tighten up the AWS ECS policy actions needed by weave

### ISSUE THREAD

**Issue by bosschaert** [weaveworks/guides#180]
I was looking at the security policy actions that are currently listed in the weave AWS ECS integration (here: https://github.com/weaveworks/guides/blob/master/aws-ecs/data/weave-ecs-policy.json). They currently list the following actions:

```
                "ecs:CreateCluster",
                "ecs:DeregisterContainerInstance",
                "ecs:DiscoverPollEndpoint",
                "ecs:Poll",
                "ecs:RegisterContainerInstance",
                "ecs:Submit*",
                "ecs:ListClusters",
                "ecs:ListContainerInstances",
                "ecs:DescribeContainerInstances",
                "ec2:DescribeInstances",
                "ec2:DescribeTags",
                "autoscaling:DescribeAutoScalingInstances"
```

Although I can guess why most of these are needed, I am in particular curious why it would need `ecs:CreateCluster/ecs:ListClusters` - weave does not create any clusters AFAIK?

Additionally it would really be helpful to have an explicit list of Submit... actions needed rather than the rather ill-defined `ecs:Submit*`. Would it be possible to provide this so that there is no need for a wild-card any more?

**Comment by errordeveloper** [comment]
I think that `ecs:ListCluster` is stale from a previous version of [`peers.sh`](https://github.com/weaveworks/integrations/blob/master/aws/ecs/packer/to-upload/peers.sh), but I let @2opremio comment. To me it definitely looks like these permissions need to be refined.
