### ISSUE TITLE
t2.micro instances in ECS guide are too anaemic

### ISSUE THREAD

**Issue by rade** [weaveworks/guides#181]
The [ECS guide/script](https://github.com/weaveworks/guides/tree/master/aws-ecs) starts t2.micro instances. These instance types operate with CPU credits. Once the credits are exhausted, the machine grinds to a halt until sufficient time passes for credits to be replenished. This makes these instances types a poor choice for experimentation, since the dramatic performance degradation can be mistaken for a problem with weave scope/net.

cc @2opremio

**Comment by 2opremio** [comment]
Yep, noticed this in https://github.com/weaveworks/scope/issues/897 but AFAIK only t2.micro instances are covered by the free tier. We could add a warning mentioning that a beefier type of instance will be needed for setups running for more than a couple of hours.

**Comment by rade** [comment]
A warning in the setup script? Won't that get drowned by the general noise?

We may also want to add some pointers for finding out whether VMs are being throttled.

**Comment by 2opremio** [comment]
> A warning in the setup script? Won't that get drowned by the general noise?

I meant the guide but we could do both. In fact we will be able to show it more explicitly when we replace the script with Cloudformation.

> We may also want to add some pointers for finding out whether VMs are being throttled.

I don't myself know how to do this but I will look into it.

**Comment by errordeveloper** [comment]
I don't see a good reason to work around this, I think we should just use m3 or other type of instances of substantial size.

**Comment by 2opremio** [comment]
> I don't see a good reason to work around this, I think we should just use m3 or other type of instances of substantial size.

Only t2.micro instances are covered by the free tier. Remember it's a guide which people probably will use for testing, we don't want them to spend money if not absolutely necessary.

**Comment by errordeveloper** [comment]
Sure, but may be that is less important whether they will spend a few
dollars or not... they will have card on file at this point anyway.

**Comment by 2opremio** [comment]
> they will have card on file at this point anyway.

I don't think we should be assuming this

**Comment by 2opremio** [comment]
Another use run into this https://weaveworks.slack.com/archives/weave-users/p1466154335000239

However, he is using t2.micro instances in production, using larger instances apparently isn't an option for him.

**Comment by errordeveloper** [comment]
When I set up my account a few years ago, I remember I couldn't do much
before I added a card.

**Comment by 2opremio** [comment]
Yes, I meant we shouldn't be assuming that people can spend money away even if the card is added.

**Comment by errordeveloper** [comment]
> Yes, I meant we shouldn't be assuming that people can spend money away even if the card is added.

Ok, that's true.

**Comment by errordeveloper** [comment]
In any case, we should start working on #175 and figure out some nice UX. Current page is [a bunch of screenshot](https://www.weave.works/deploy-weave-aws-cloudformation-template/), and it can be turned into a much more enhanced experience, where people will learn information like what's being discussed here. We can also consider merging it with the current plain text guide or linking in some cleaver way.

**Comment by rade** [comment]
Perhaps we should add a note somewhere explaining the symptoms and linking to instructions for discovering when instances have been throttled.
