### ISSUE TITLE
Failed to scale web=3

### ISSUE THREAD

**Issue by ghost** [weaveworks/guides#182]
guides/weave-and-docker-platform/scripts
https://www.weave.works/guides/part-3-creating-and-scaling-multi-host-docker-deployment-with-swarm-and-compose-using-weave/

WARNING: The "web" service specifies a port on the host. If multiple containers for this service are created on a single host, the port will clash.
Creating and starting app_web_2 ... error
Creating and starting app_web_3 ... error

ERROR: for app_web_2  Unable to find a node that satisfies the following conditions 
[port 80 (Bridge mode)]

ERROR: for app_web_3  Unable to find a node that satisfies the following conditions 
[port 80 (Bridge mode)]

**Comment by abuehrle** [comment]
Thanks for the report. Can you tell us in which guide you're encountering this issue?

**Comment by ghost** [comment]
The part 3 of the guide. and try to scale web=3 with docker-compose failed

my docker info:

```
Containers: 9
 Running: 9
 Paused: 0
 Stopped: 0
Images: 7
Server Version: swarm/1.2.3
Role: primary
Strategy: spread
Filters: health, port, containerslots, dependency, affinity, constraint
Nodes: 3
 weave-1: 163.172.151.73:12375
  └ ID: STPU:UNF7:4QY2:KGKN:SKVQ:XGKK:RVGF:MFSE:6TY3:ZO4Z:I7TB:4W6H
  └ Status: Healthy
  └ Containers: 9
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 2.052 GiB
  └ Labels: executiondriver=, kernelversion=4.5.4-docker-1, operatingsystem=Ubuntu 16.04 LTS, provider=scaleway(VC1S), storagedriver=aufs
  └ UpdatedAt: 2016-06-08T01:30:34Z
  └ ServerVersion: 1.11.2
 weave-2: 163.172.157.208:12375
  └ ID: MY7E:55H3:LWY3:NQFX:MJNT:MB3W:Y2ML:2ZNS:2CYI:27WG:36M3:BLQI
  └ Status: Pending
  └ Containers: 0
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 2.052 GiB
  └ Labels: executiondriver=, kernelversion=4.5.4-docker-1, operatingsystem=Ubuntu 16.04 LTS, provider=scaleway(VC1S), storagedriver=aufs
  └ UpdatedAt: 2016-06-08T01:30:11Z
  └ ServerVersion: 1.11.2
 weave-3: 163.172.161.153:12375
  └ ID: UHXC:KOJP:LQLS:TM4A:5HO2:QASJ:YQ75:ZUDX:ASKJ:HGZM:FGSD:CRHX
  └ Status: Pending
  └ Containers: 0
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 2.052 GiB
  └ Labels: executiondriver=, kernelversion=4.5.4-docker-1, operatingsystem=Ubuntu 16.04 LTS, provider=scaleway(VC1S), storagedriver=aufs
  └ UpdatedAt: 2016-06-08T01:30:11Z
  └ ServerVersion: 1.11.2
Plugins: 
 Volume: 
 Network: 
Kernel Version: 4.5.4-docker-1
Operating System: linux
Architecture: amd64
CPUs: 2
Total Memory: 2.052 GiB
Name: 80d34debbb53
Docker Root Dir: 
Debug mode (client): false
Debug mode (server): false
WARNING: No kernel memory limit support

```

**Comment by abuehrle** [comment]
Docker compose needs to be version 2, which currently it isn't in the guide.  Please have a look at this issue which might solve your problem: 

https://github.com/weaveworks/guides/issues/178

Otherwise, maybe @errordeveloper might be able to help.

**Comment by errordeveloper** [comment]
https://github.com/weaveworks/guides/pull/186 should solve this.
