### ISSUE TITLE
Enable code highlighting where appropriate

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/guides#21]
See [kramdown docs](http://kramdown.gettalong.org/quickref.html#code-blocks).

**Comment by errordeveloper** [comment]
Also, indented blocks are pretty nasty to deal with, so we should get rid of them.

**Comment by errordeveloper** [comment]
Liquid macros are nasty too, too long to type and remember.

**Comment by abuehrle** [comment]
Needs to be enabled in the website now.
