### ISSUE TITLE
don't make `--probe.no-controls` part of c&p code

### ISSUE THREAD

**Issue by rade** [weaveworks/guides#210]
https://www.weave.works/guides/visualizing-microservices-with-weave-cloud-docker-for-mac/#connect-scope-probe-to-weave-cloud has

```
scope launch --service-token=<YOUR_WEAVE_CLOUD_SERVICE_TOKEN> --probe.no-controls
```

I understand why we may want to mention the `--probe.no-controls` option, but having it as part of the command that users will likely copy & paste is bad since it means they will be missing out on a whole bunch of scope features.

**Comment by rade** [comment]
What's more, that guide actually goes on and tells users to open a terminal in scope, which won't work if they have specified `--probe.no-controls`!

**Comment by abuehrle** [comment]
read the comment. It also says:

 "sets controls to read-only access for all users. This flag is optional."

**Comment by rade** [comment]
I did read the comments. My point is that most people won't, or at the very least they will think that supplying that option is a sensible default. And they will just c&p what is there.

**Comment by abuehrle** [comment]
Good to see you finally reviewing a guide.

**Comment by lukemarsden** [comment]
I suggest that we make it clear to users that they have the choice, something like:

> `scope launch --service-token=<YOUR_WEAVE_CLOUD_SERVICE_TOKEN>`
> By default, this will enable features of the Scope & Cloud including opening a terminal on the host and inside containers. If you don't want to enable this functionality for security reasons, please add the `--probe.no-controls` to the end of the `scope launch` command, which will disable "write" operations from the Cloud UI: this will make Scope Probe only _push_ metrics to Cloud.

**Comment by abuehrle** [comment]
I changed it to: 

Note: To set the Weave Cloud controls to read-only for all users, you can launch scope with the --probe.no-controls.  But since you will be launching a terminal window and viewing messages between microservices, this flag is not necessary. However, you may want to keep this flag in mind when using Weave Cloud and sharing your infrastructure with others.

**Comment by lukemarsden** [comment]
OK, that's good too – I would define what you mean by "Weave Cloud controls" though.

**Comment by lukemarsden** [comment]
Looks like there are some formatting issues on the guide now btw.

**Comment by abuehrle** [comment]
Yeah, fixed it.

**Comment by lukemarsden** [comment]
In particular, "Where," is now mistakenly part of the code block.

**Comment by abuehrle** [comment]
can we take this offline?
