### ISSUE TITLE
Guide update required

### ISSUE THREAD

**Issue by mindnuts** [weaveworks/guides#228]
Hi...Atleast two of the guides (coreos-simple and weave-loadbalance) are broken. Can you please fix them?

**Comment by errordeveloper** [comment]
@mindnuts thanks for reporting this. I'm afraid these particular guides are no longer actively maintained. What is it that you wanted to learn from these? I'd be happy to speak [on Slack](https://weaveworks.github.io/community-slack/) and help you out with any specific questions.
