### ISSUE TITLE
flux private registry instructions are wrong.

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/guides#233]
On the quay setup, "Launching and Configuring Flux", step 5, it says to go `View Credentials` then `Docker Login`, but instead of `Docker Login` it should be `Docker Configuration`, then `</> View something-here-i-dont-know-what.json`, to get the base64-encoded auth value.

**Comment by abuehrle** [comment]
thanks @paulbellamy will fix this ASAP.

**Comment by abuehrle** [comment]
updated via 686e2e1a66104aaf9ab31e385e3edb7d57ec4904
