### ISSUE TITLE
Docker toolbox

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/guides#24]
Should use it in platform guide.

**Comment by abuehrle** [comment]
just working on those guides now

**Comment by errordeveloper** [comment]
It's best if we pin the download URLs, so we can make sure users get what had been tested.
- OS X: `https://github.com/docker/toolbox/releases/download/v1.8.1/DockerToolbox-1.8.1.pkg`
- Windows: `https://github.com/docker/toolbox/releases/download/v1.8.1/DockerToolbox-1.8.1.exe`

We should check the status of linux one too...

**Comment by errordeveloper** [comment]
For the record, we cannot use the `Docker Quickstart Terminal.app` in a sensible manner...

**Comment by errordeveloper** [comment]
I've tested https://github.com/weaveworks/weave/pull/1291 with toolbox 1.8.1 and it works.

**Comment by abuehrle** [comment]
What did you set the DOCKER_HOST to for the proxy because I couldn’t get it to work at all. 

Maybe it’s something with my system setup?
