### ISSUE TITLE
Cloud Guide pt 1 - load test instruction is incomplete

### ISSUE THREAD

**Issue by pidster** [weaveworks/guides#255]
https://www.weave.works/guides/cloud-guide-part-1-setup-troubleshooting/

The load-test container command does not include the `--net` param that allows it to join a network and find the `edge-router` container, by name.

**Comment by abuehrle** [comment]
thanks for this @pidster

**Comment by abuehrle** [comment]
Fixed loadtest for local run sockshop and added manual instructions for kubernetes.
