### ISSUE TITLE
Pitfall in guides for setting up the Kubernetes cluster in Digital Ocean

### ISSUE THREAD

**Issue by mongrelion** [weaveworks/guides#269]
The [current version of the guides](https://github.com/weaveworks/guides/blob/4a344d3516355984b4056a32e01e67e4bc557680/weave-cloud-microservices/includes/setup-kubernetes-sock-shop.md) for setting up a Kubernetes cluster in Digital Ocean and deploying the Socks Shop to it has a pitfall on the step **[#5 Initialise the Master](https://github.com/weaveworks/guides/blob/4a344d3516355984b4056a32e01e67e4bc557680/weave-cloud-microservices/includes/setup-kubernetes-sock-shop.md#5-initialize-the-master)**

It says:
>If you want to use a different network interface, you can specify one using `--api-advertise-addresses=<ip-address>` flag when you run kubeadm init.

In other cases this might work but in Digital Ocean it won't if you're using the Private Network option. The reason why you want to use the Private Network option for your droplets is that you don't want the nodes in the cluster to talk to each other over Internet when they are in the same datacenter. So, by default, from the guides, this is exactly the case: the cluster gets setup using the public IP that the droplets receive by default and these IPs are accessible from Internet, meaning two things:
1. The nodes are talking to each other over Internet
2. All the nodes in the cluster (master & workers) are directly accessible from the open Internet.

In theory the `--api-advertise-addresses` flag should fix this problem but in practice it doesn't. See issue [#203](https://github.com/kubernetes/kubeadm/issues/203) from the [kubernetes/kubeadm](https://github.com/kubernetes/kubeadm) repository.

I suggest to either
- Remove the suggestion to use the `--api-advertise-addresses` flag from the guides
- Explain why, even thought it's an option available, why people can't really use it as of right now.

It's also important to say in the guides that the cluster will be open to the Internet and maybe offer some sane defaults for protecting it from attacks (some easy firewall rules with `ufw`).

**Comment by lukemarsden** [comment]
Thanks @mongrelion! Please make a PR against https://github.com/weaveworks/website-next

**Comment by mongrelion** [comment]
@lukemarsden I don't have access to that repo. Could you please hook me up with that?

**Comment by lukemarsden** [comment]
@mongrelion done!

**Comment by mongrelion** [comment]
@lukemarsden https://github.com/weaveworks/website-next/pull/60
