### ISSUE TITLE
Could we make the systemd unit files official?

### ISSUE THREAD

**Issue by Lawouach** [weaveworks/guides#29]
Hi,

I see the CentOS Mesos/Marathon guide provides its own systemd unit files. I find them quite valuable but I'd feel more confident if they were made official somehow. Could they be made part of the main weave repository?

Docker provides similar unit files too: https://github.com/docker/docker/tree/master/contrib/init/systemd

Thanks,

**Comment by errordeveloper** [comment]
@Lawouach that's a good question! However, I running containers from within systemd is a bit tricky and there is no best way of doing it. I had been trying different approaches and still not convinced which is best to turn into official. Potentially using runc would be a better call, to be very honest.

**Comment by errordeveloper** [comment]
There is also a question of how should know peers be preserved, see #10.

**Comment by Lawouach** [comment]
> running containers from within systemd is a bit tricky 

I wouldn't mind if you could expand on this a bit, out of curiosity.

> Potentially using runc would be a better call, to be very honest.

It would be an interesting path indeed. The docker daemon always felt like an unecessary evil to me.

**Comment by errordeveloper** [comment]
You might want to take a look at the units show in our recent [Mesos guide](http://weave.works/guides/platform/mesos-marathon/os/centos/cloud/vagrant/index.html), e.g. [`weave.service`](https://github.com/weaveworks/guides/blob/master/mesos-marathon/centos/weave.service).

**Comment by errordeveloper** [comment]
> > running containers from within systemd is a bit tricky 
> 
> I wouldn't mind if you could expand on this a bit, out of curiosity.

Ok, so the basic issue is that Docker daemon wants to own it's children, and that's technically what systemd desires to do as well. So it's a bit tricky, I've been using `docker attach` for now, but that doesn't give systemd direct control, as signals would still get proxied to Docker. So you then have to set a stop command, and, in turns, ignore some additional exit codes etc...

> > Potentially using runc would be a better call, to be very honest.
> 
> It would be an interesting path indeed. The docker daemon always felt like an unecessary evil to me.

That's right ;)

**Comment by Lawouach** [comment]
I see. I think this is why the guys behind Rancher say that using Docker on CoreOS is rather counter-productive.

**Comment by errordeveloper** [comment]
It's not that bad :smile:
