### ISSUE TITLE
Links in Chapter 3 Broken?

### ISSUE THREAD

**Issue by garystafford** [weaveworks/guides#36]

**Comment by garystafford** [comment]
If I go to guides / weave-and-docker-platform / 3-machine-weaveproxy-swarm.md, and click on many of the links, like the shell scripts links, they are broken. Maybe that is just misusing the guide as intended by clicking on markdown files directly to read?
Like, "It is very easy to script this first step and you can find my implementation in [scripts/1-machine-create.sh](https://github.com/errordeveloper/weave-demos/blob/master/quartet/scripts/1-machine-create.sh)."

**Comment by errordeveloper** [comment]
You should access the guide through [the website](http://weave.works/guides/weave-and-docker-platform/chapter3/machine-and-swarm-with-weave-proxy.html).

**Comment by garystafford** [comment]
Thank you.

**Comment by errordeveloper** [comment]
@garystafford could please explain how did you arrive at the document? Did you, by any chance, use GitHub search or you just navigated around repositories under Weaveworks organisation?

**Comment by garystafford** [comment]
@errordeveloper yes, I navigated around repo to specific page I needed to reference.
