### ISSUE TITLE
Multi-distro guides

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/guides#38]
I have just made a few quite simple changes to the Mesos guide that make it run on Ubuntu instead of CentOS.

It's not hard to arrange scripts and Vagrantfile to handle small differences between distros and save users some time, especially that it's now a given most distros use systemd and it's all about Docker.

However, It's not feasible to maintain a copies of text, so I think we can have a simple selector button.

In the guide, one can write markdown like this:

```
~~~ bash
[root@mesos-01 vagrant]# docker run -ti centos:7
[root@7844aae5d94d /]# curl outyet:8080
~~~
{: .for-centos }

~~~ bash
[root@mesos-01 vagrant]# docker run -ti ubuntu:15.04
[root@7844aae5d94d /]# apt-get install curl
...
[root@7844aae5d94d /]# curl outyet:8080
~~~
{: .for-ubuntu }
```

And with a tiny bit of JavaScript we can flip around instructions for the distro user has picked.

**Comment by errordeveloper** [comment]
I suppose we can also pretty much get rid of mentioning OS in the text, there would be just a button for user to pick one.

**Comment by errordeveloper** [comment]
If we look at the Spring guides layout, this fits nicely on right above "Get Code" widget.

**Comment by dpw** [comment]
Such an approach is great for the audience, but it still takes a lot of work to check that the instructions are correct for each OS covered.

I wonder if its feasible to automatically validate the instructions by running them somewhere. But maybe getting that to work is a lot of work too.

**Comment by davkal** [comment]
@dpw we need an intern.

But on a more serious note, we could use includes for certain re-occurring steps a la 

```
{% include install-weave-ubuntu %}
```

Then we can update them centrally.

**Comment by errordeveloper** [comment]
> But on a more serious note, we could use includes for certain re-occurring steps

Good point!

> I wonder if its feasible to automatically validate the instructions by running them somewhere. But maybe getting that to work is a lot of work too.

There two aspects that I can see:
1. Automation and infrastructure (not too hard)
2. Validation of results (harder, as one needs to pick the depth at which most errors would get detected)

Nevertheless, I'd love to do that.

**Comment by abuehrle** [comment]
In the past, when I had to deal with multiple OS's we would just make very clear headings in the text, when the instructions diverged between OS'. 

If it's just small changes, then there is little point in maintaining multiple files with the same instructions.  Of course, if they diverge greatly, then a different file is warranted.  It's a lot more work to maintain all these different files, then it is to just include the differences into one file.

**Comment by errordeveloper** [comment]
I think it would be really great to try and do at least start some basic automated testing before we jump into this, so I opened #94 for that discussion.
