### ISSUE TITLE
The script "setup.sh" in guides/aws-ecs doesn't work

### ISSUE THREAD

**Issue by imshashank** [weaveworks/guides#49]
The script has stopped working and fails to see that the response from aws contains "<Response [200]>" in the response.

The cluster check "ACTIVE/INACTIVE" fails..Also the "SECURity_GROUP" fails and SUBNET fails !!

These variables are improperly set.

**Comment by rade** [comment]
Do you have a transcript of a failing run of the script?

**Comment by rade** [comment]
The OP says...

Using the scirpt I had these problems:

```
# Check that setup wasn't already run
CLUSTER_STATUS=$(aws ecs describe-clusters --clusters weave-ecs-demo-cluster --query 'clusters[0].status' --output text)
if [ "$CLUSTER_STATUS" != "None" -a "$CLUSTER_STATUS" != "INACTIVE" ]; then
    echo "error: ECS cluster weave-ecs-demo-cluster is active, run cleaup.sh first"
    exit 1
fi
```

This line asks to run cleanup.sh always as the “if” doesn’t account for the `<Response [200]>` returned with the response.

Also the same things happen with:

```
SECURITY_GROUP=$(aws ec2 create-security-group --group-name weave-ecs-demo --description 'Weave ECS Demo' --query 'GroupId' --output text)
SUBNET=$(aws ec2 describe-subnets --query 'Subnets[0].SubnetId' --output text)
```

The variables are improperly set and results in error.

I changed my aws cli response to “json/text etc.” all gave the same errors.

I am running AWS CLI on mac osx.

Also there were bunch of other errors, including the security group not having the VPC id set and hence was unable to start the EC2 containers.

**Comment by rade** [comment]
> `<Response [200]>` returned with the response.

It seems rather odd to get this back in the output.

> I am running AWS CLI on mac osx.

I wonder whether that is the issue.

**Comment by rade** [comment]
@imshashank what does `aws --version` report for you?

**Comment by imshashank** [comment]
This was the reply from "aws --version"

aws-cli/1.7.45 Python/2.7.10 Darwin/14.4.0

**Comment by imshashank** [comment]
Also on aws configure the "Default output format" is set to "json"

**Comment by rade** [comment]
I have just done a completely fresh [install of the AWS CLI tools via the bundler](http://docs.aws.amazon.com/cli/latest/userguide/installing.html#install-bundle-other-os) on my "3.16.0-46-generic #62~14.04.1-Ubuntu" desktop:

```
$ aws --version
aws-cli/1.8.0 Python/2.7.6 Linux/3.16.0-46-generic
```

I then created myself an IAM user in AWS, created a security group with admin privileges, added the user to that group, created and downloaded an access key for the user, ran `aws configure`, as per the guide, and then ran

```
$ ./setup.sh 
Creating ECS cluster (weave-ecs-demo-cluster) .. done
Creating Security Group (weave-ecs-demo) .. Done
Creating Key Pair (weave-ecs-demo, file weave-ecs-demo-key.pem) .. done
Creating IAM role (weave-ecs-role) .. done
Creating Launch Configuration (weave-ecs-launch-configuration) .. done
Creating Auto Scaling Group (weave-ecs-demo-group) with 3 instances .. done
Waiting for instances to join the cluster (this may take a few minutes) .. done
Registering ECS Task Definition (weave-ecs-demo-task) .. done
Launching (3) tasks .. done
Waiting for tasks to start running .. done
Setup is ready!
Open your browser and go to any of these URLs:
  http://ec2-52-18-154-163.eu-west-1.compute.amazonaws.com
  http://ec2-52-18-60-156.eu-west-1.compute.amazonaws.com
  http://ec2-52-18-108-68.eu-west-1.compute.amazonaws.com
```

So this all appears to have worked.

> on aws configure the "Default output format" is set to "json"

Mine was set to 'None' but I've just re-run with 'json' and it still works.

**Comment by imshashank** [comment]
I think its a "mac" issue then. Coz each reply from aws cli has `"<response...>"` with makes the variable not usable.

**Comment by rade** [comment]
Yes, looks like a Mac issue though I am quite sure some of my Mac-loving colleagues have run the script. So it's likely some package version / config issue.

**Comment by rade** [comment]
> I am quite sure some of my Mac-loving colleagues have run the script.

@abuehrle has had this working on her Mac with `aws-cli/1.7.41 Python/2.7.10 Darwin/14.4.0`.

> So it's likely some package version / config issue.

and likely something other than the aws-cli, python and OSX versions. My money would be on some python package. Did you install the aws-cli from the bundle or using 'pip'? If the latter, it might be worth trying the former.

**Comment by imshashank** [comment]
ok will give it a try..and keep you updated.. Thanks for the help :-)

**Comment by 2opremio** [comment]
I've just run `setup.sh` in my OSX machine (which I also tested on OSX before releasing the guide) and works fine.

These are my system details:

```
$ aws --version
aws-cli/1.7.39 Python/2.7.10 Darwin/14.4.0
```

I installed aws with pip but I am not sure this is relevant.

I am with @rade. The problem is most likely environmental and python-related. @imshashank how did you install the aws CLI? Did you, by any change, modify the python libraries or are running non standard ones? 

The aws CLI is not supposed to print out HTTP reply status codes.

**Comment by 2opremio** [comment]
@imshashank Did you figure out what was wrong?

**Comment by pidster** [comment]
Bump. Will close in 7 days if there's no response.

**Comment by 2opremio** [comment]
@imshashank

**Comment by alex88** [comment]
Here there is no `weave-ecs-role.json` file, at least following the manual setup
