### ISSUE TITLE
bring guides up-to-date wrt weave 1.0 best practice; make consistent with main docs

### ISSUE THREAD

**Issue by rade** [weaveworks/guides#5]
Most of the guides pre-date 1.0 and thus are inconsistent with the main docs.

In particular they should:
- always launch weave with

```
weave launch && weave launch-dns && weave launch-proxy
eval $(weave proxy-env)
```

(modulo variations to launch args)
- always start containers with docker, through the proxy, never with `weave run`
- always take advantage of ipam and naming; there should be no IP addresses in sight
- always let hostnames derive from container names; never specify hostnames with `-h`
- always address containers by their short name instead of fqdn
- always rely on the default IPAM subnet; never configure IPAM with an explicit subnet

...unless there are very specific reason to do something different.

There are probably more. Take a look at the main docs to get a feel for how weave is meant to be used to these days.

**Comment by ryc8889** [comment]
Are there any reasons why we should not specify hostnames with -h ? On AWS EC2 instances i never had an issue with specifying hostnames with -h and having my containers communicate with each other over the weave network but on CentOS 7, it is causing me some issues with containers discovering each other using the specified hostnames.

**Comment by bboreham** [comment]
It's just less confusing to set the container name and let the hostname be derived from it.  Then there is only one visible name, and it's the same name in all contexts.

Nothing wrong with setting the hostname separately, if you know what you are doing.

Please raise an issue at https://github.com/weaveworks/weave for the problem with containers discovering each other, or use one of the other communications channels listed at https://www.weave.works/help/
