### ISSUE TITLE
kubernetes + weave 1.1 guide fails with "No such image"

### ISSUE THREAD

**Issue by rade** [weaveworks/guides#55]
See https://github.com/weaveworks/weave/issues/1392

**Comment by rade** [comment]
@abuehrle you reported this as a failure of `weave expose`, but the logs indicate that things went wrong before then:

>  `weaveproxy.service: Start-pre operation timed out. Terminating.`

Also, there is

> `Sep 05 22:39:21 kube-01 weave[1265]: Repository weaveworks/weaveexec already being pulled by another client. Waiting.`

So I suspect you've hit that well known docker issue where sometimes it will be stuck forever downloading some images.

**Comment by errordeveloper** [comment]
The issue is to do with missing a explicit `docker pull`, so and as units get launched in parallel, it hits this .  It was originally in place, but then got remove for a different reason that no longer applies. I have add `weave setup` in ce739df565cdbfb18cc6e19c4779dac134fceca8.
