### ISSUE TITLE
Split Kubernetes Vagrant script into logical parts 

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/guides#58]
I would split this script into 3 or 4 parts to make it easier to debug when something fails. 

For example, a script would be created for each step listed below, which we can explain in the Guide: 
1. provision VMs. with CoreOS cluster
2. launch weave
3. Deploy Kubernetes
4. Deploy app

**Comment by errordeveloper** [comment]
I absolutely makes sense to have a guide that show manual steps. However, I am quite sure that users who chose CoreOS and Weave would be able to derive what they need from #52 and we should address new user concerns via #63 instead and base it on a more traditional OS.
