### ISSUE TITLE
"'chef/centos-7.0' could not be found" error

### ISSUE THREAD

**Issue by rade** [weaveworks/guides#59]
Reported by a user...

> I was trying to test http://weave.works/guides/weave-docker-centos-simple.html
> 
> But when I run “vagrant up” I’ve got this error:
> 
> ```
> Bringing machine 'weave-gs-01' up with 'virtualbox' provider...
> Bringing machine 'weave-gs-02' up with 'virtualbox' provider...
> ==> weave-gs-01: Box 'chef/centos-7.0' could not be found. Attempting to find and install...
>    weave-gs-01: Box Provider: virtualbox
>    weave-gs-01: Box Version: >= 0
> The box 'chef/centos-7.0' could not be found or
> could not be accessed in the remote catalog. If this is a private
> box on HashiCorp's Atlas, please verify you're logged in via
> `vagrant login`. Also, please double-check the name. The expanded
> URL and error message are shown below:
> URL: ["https://atlas.hashicorp.com/chef/centos-7.0"]
> Error: The requested URL returned error: 404 Not Found
> ```
> 
> It seems to fail because the image “chef/centos-7.0” no longer exist, I have tested with “wlc/centos-7.0” and it worked but I’ve got other error related to Virtual Box Guest Additions and I’m stuck on it. (using Vagrant 1.7.4 and Virtual Box 5.0.2).
> 
> Other guides have the same problem with the non existing 'chef/centos-7.0' image.

**Comment by errordeveloper** [comment]
I have attempted switching the image to 7.1, but I think it's best to just update the guide for 1.1 entirely and make sure it's has very minor difference against the Ubuntu one, so we can proceed to prototyping something for #38.

**Comment by ku1ik** [comment]
Just a note for people finding this issue via Google search: there's a copy of `chef/centos-7.0` box here: https://atlas.hashicorp.com/grtjn/boxes/centos-7.0

**Comment by mgirouard** [comment]
We had similar issues on an unrelated repo. Adding notes for posterity.

It looks like the base box was killed for some reason. It also seems like all the `chef/*` boxes have moved over to `bento/*`

@sickill et. al. — unless you _really_ need Cent 7.0, it's best to use 7.1. You can update your `Vagrantfile` to use `bento/centos-7.1`
