### ISSUE TITLE
Formatting issue with weave+docker chapters

### ISSUE THREAD

**Issue by davkal** [weaveworks/guides#64]
1. Could we get rid of chapter? Maybe use Part? Or just no prefix?
2. Use same yellow box on the [overview page](http://weave.works/guides/weave-and-docker-platform/index.html) as on the chapter pages.

![](https://s3-eu-west-1.amazonaws.com/uploads-eu.hipchat.com/175221/1726049/eGi2tujP70mqbRn/website.png)

**Comment by paulbellamy** [comment]
Or could try making it `col-md-3` and losing the offset?

**Comment by davkal** [comment]
@paulbellamy I dont like that it's inconsistent with the display on the chapter pages. So I'd rather advise making that harmonious.

**Comment by abuehrle** [comment]
I re-wrote that chapter and have just merged the changes into the guides. Is it possible to update the guides on the website?  Yes, totally got rid of 'chapter' and I also merged the first 2 parts into 1, so there are 3 parts to this now.  Also, incorporated the 1.1 changes.

**Comment by kpoplin** [comment]
It may be too late but I really like calling these “part 1” vs chapter 1 vs no prefix. That encourages completion, makes it stickier to the reader, a little psychological difference...

**Comment by abuehrle** [comment]
Thanks @kpoplin.  I’ve changed them to Parts, totally agree.   Look, we’ve rolled out a new sidebar:

http://weave.works/guides/index.html http://weave.works/guides/index.html 

The index page still needs styling, which I’d really like some feedback/ideas on.
