### ISSUE TITLE
guides aws-ec2 setup fails

### ISSUE THREAD

**Issue by ichekrygin** [weaveworks/guides#65]
~/s/g/w/g/aws-ecs  master  ./setup.sh                                                                                                                                                                    [85/393]
Creating ECS cluster (weave-ecs-demo-cluster) .. done
Creating Security Group (weave-ecs-demo) .. Done
Creating Key Pair (weave-ecs-demo, file weave-ecs-demo-key.pem) .. done
Creating IAM role (weave-ecs-role) .. done
Creating Launch Configuration (weave-ecs-launch-configuration) .. done
Creating Auto Scaling Group (weave-ecs-demo-group) with 3 instances .. done
Waiting for instances to join the cluster (this may take a few minutes) .. ^C⏎   

It appears that it fails to launch Auto Scaling Group: 
Launching a new EC2 instance. Status Reason: The security group 'sg-2d396c40' does not exist in VPC 'vpc-d69ff8bb'. Launching EC2 instance failed.

Looks like setup creates a security group that is not attached to any VPC. Also, it appears that setup does not create a dedicated VPC for weave-ecs-demo-cluster.

**Comment by errordeveloper** [comment]
@ichekrygin thank you for reporting this! We have made several update to the ECS guide, could you please check and reopen if this is still an issue...
