### ISSUE TITLE
Mac instructions are missing `weave launch-router`

### ISSUE THREAD

**Issue by rade** [weaveworks/guides#66]
In http://weave.works/guides/weave-and-docker-platform/weavenetwork.html we explain "Launching weaveproxy if You are Running OSX", but nowhere do we say that you also need to run `weave launch-router`.

**Comment by abuehrle** [comment]
does `weave launch` not launch the router and weavedns?   I thought that only the proxy was not launching on the Mac because of the TLS settings. Are you telling me that I need to also start the router as well.  So, should I be including the old instructions here for the Mac?

**Comment by rade** [comment]
> does `weave launch` not launch the router and weavedns

Yes, but it _also_ launches the proxy. And here we need to launch the proxy separately. Which means we need to launch the router separately.

From the 1.1 release notes...

> For the proxy, if the existing installation ... was launching the proxy with options, then you need to launch the router and proxy separately, supplying the proxy options to the latter, i.e. `weave launch-router && weave launch-proxy <options>`

**Comment by abuehrle** [comment]
I've changed the heading from Launching Weave Proxy on OS X to Launching Weave on OSX, which now includes launching the router as well as proxy.  Before it was assumed that weave launch does in fact launch the router, but didn't launch proxy,  because of TLS on the mac.
