### ISSUE TITLE
typos in swarm guide

### ISSUE THREAD

**Issue by rade** [weaveworks/guides#72]
Some stutter in http://weave.works/guides/weave-and-docker-platform/using-weave-with-machine-and-swarm.html:

> and finally, set the weave environment variable for weave-1
> 
> `eval "$(weave env)"`
> 
> Set the weave env for weave-1
> 
> `eval "$(weave env)"`

**Comment by rade** [comment]
Also, http://weave.works/guides/weave-and-docker-platform/using-weave-with-machine-and-swarm.html says

> On weave-1 run:
> 
> `weave launch`
> 
> Specify the TLS settings if asked:
> 
> `tlsargs=$(docker-machine ssh weave-12 \
>  "cat /proc/\$(pgrep /usr/local/bin/docker)/cmdline | tr '\0' '\n' | grep ^--tls | tr '\n' ' '")`
> 
> launch the proxy using the TLS settings you grepped above:
> 
> `weave launch-proxy $tlsargs`

That `weave launch` should be `weave launch-router`

**Comment by abuehrle** [comment]
fixed
