### ISSUE TITLE
remove TLS hacks post 1.2

### ISSUE THREAD

**Issue by rade** [weaveworks/guides#73]
Per https://github.com/weaveworks/weave/pull/1414#issuecomment-140035091...

http://weave.works/guides/weave-and-docker-platform/weavenetwork.html and http://weave.works/guides/weave-and-docker-platform/using-weave-with-machine-and-swarm.html and https://github.com/weaveworks/guides/blob/6db6ee1e11d7e37d30506095620cfccb03dbbefa/weave-and-docker-platform/scripts/2-weave-launch.sh need updating - they all feature the TLS hack, the need for which has been eliminated (in the upcoming weave 1.2). Which also means the router and proxy can now be launched together with `weave launch`.

**Comment by abuehrle** [comment]
Fixed.
