### ISSUE TITLE
I'm a sad Panda :) - weave-and-docker-platform

### ISSUE THREAD

**Issue by pierreozoux** [weaveworks/guides#79]
I tried various things, I just didn't manage to get anything working...

https://microblog.pierre-o.fr/2015/docker-global-hackday---weave-fail

I had everything uptodate (docker, machine, compose). I used digitalocean as provider. My machine is ubuntu.

It is hard to tell what is the issue as there were many. Just try it again, and I think you'll see. I'd be really happy to make it working!

Tell me how we could manage together :)

Best, and thanks for your work :)

**Comment by bboreham** [comment]
@pierreozoux we have clarified the text and updated the scripts.  If you get a chance to try it again, let us know how it goes.

If it goes wrong again, please can you include some specific details, e.g. the error message.

**Comment by pierreozoux** [comment]
@bboreham ok, thanks!

I'll try when I'll have time.
