### ISSUE TITLE
Improvements to weave-and-docker-platform guide

### ISSUE THREAD

**Issue by bboreham** [weaveworks/guides#84]
I worked through the guide, and jotted down some notes:

The script `scripts/1-machine-create.sh` repeats 4 lines, which is a potential source of error.

> Next launch Weave onto each of the virtual machines.
> On weave-1 run:

It is not made very clear how you specifically go about doing this. I think you are supposed to do `eval "$(docker-machine env weave-1)"` then run `weave`.

[note: the split between `weave launch-router` and `weave launch-proxy` could be avoided if the script split off the tls arguments, or `weaver` ignored them.]

> weave-1 is the bootstrap node, and so its target should be 0. Only weave-2 and weave-3 need to have --init-peer-count set to 3 at launch

This distinction is unnecessary, and indeed is not followed by the script provided.

> and finally, set the weave environment variable for weave-1 
> eval $(weave env)

Setting this is a bad idea at this point, since on the next line we need to point the docker CLI at weave-2.

> Specify the TLS settings if asked:

It is unnecessary to re-set `$tlsargs`, since it doesn't vary from machine to machine.

> Check that they are in a Swarm:

The guide doesn't say which part of the output indicates a Swarm, or what to do if you see something different.

> like we did in the two previous chapters.

we are in chapter 2 right now; how come there are two previous chapters?

> Before we tear down these two running containers,

this part does not go as described because the `nc` has exited upon connection closure, hence the "pingme" container does not appear in the list.

**Comment by abuehrle** [comment]
I've addressed these issues and have also tested the samples on my machine.
