### ISSUE TITLE
`weave launch` failing with TLS-related error

### ISSUE THREAD

**Issue by rade** [weaveworks/guides#85]
in http://weave.works/guides/weave-and-docker-platform/weavenetwork.html

[Reported on IRC](https://botbot.me/freenode/weavenetwork/2015-09-28/?msg=50676963&page=1)

I have no idea how docker-machine decides what the listen on, but evidently OSX isn't the only platform on which it will listen with TLS only.

This issue will go away with weave 1.2 since we auto-configure TLS there. Meanwhile I suggest we update the guide, perhaps with a note on the `weave launch` saying "If this fails with ... then follow the 'Launching Weave with TLS' instructions instead", and rename the OSX instructions to "Launching Weave with TLS".

**Comment by bboreham** [comment]
Noting that [part 2](http://weave.works/guides/weave-and-docker-platform/using-weave-with-machine-and-swarm.html) of the guide unconditionally does the tls thing.

**Comment by rade** [comment]
A [user reports](https://botbot.me/freenode/weavenetwork/2015-09-28/?msg=50685414&page=1)

>  there are also problems with the second script from there: http://weave.works/guides/weave-and-docker-platform/using-weave-with-machine-and-swarm.html
>  ./2-weave-launch.sh
> "When launching the proxy via TLS, -H and/or TLS options are required."

**Comment by bboreham** [comment]
The script links are very old versions; that is fixed in #86

**Comment by abuehrle** [comment]
I have fixed this #86
