### ISSUE TITLE
'git clone' instructions are inconsistent

### ISSUE THREAD

**Issue by bboreham** [weaveworks/guides#87]
Sometimes you end up in 'weaveworks-guides', sometimes in 'guides', sometimes in 'weaveworks/guides'.

At least in weave-and-docker-platform; whoever fixes this should scan the whole repo.

Note that if you have done a 'git clone' following one set of instructions, and then we change the location, the old files stick around to trip you up later.

**Comment by errordeveloper** [comment]
Yes. I think it should be 'weaveworks-guides` everywhere, or we split each guide into it's own repo.

**Comment by abuehrle** [comment]
@ilya  I have been using the following, since this is how the user actually clones the repo and then changes to the appropriate directory: 

```
git clone https://github.com/weaveworks/guides
cd ./guides/weave-and-docker-platform
```

**Comment by errordeveloper** [comment]
@abuehrle yes, so may be repo URL can be changed to `https://github.com/weaveworks/weave-guides`...

However, personally, I'd vote to either split each guide into it's own repo, OR, as @tomwilkie suggested, we can generate tarballs on the fly with some kind of proxy he wanted to write. Both approaches improve beginner-level user experience and as well as provide us with an insight into usage. Actually, Tom's approach removes the dependency on git, not that I think it's a critical one.

**Comment by abuehrle** [comment]
URLs should be consistent now.
