### ISSUE TITLE
don't ship a local copy of the weave script

### ISSUE THREAD

**Issue by bboreham** [weaveworks/guides#88]
There is a copy of `weave` in guides/weave-and-docker-platform/scripts, called from at least one of the scripts.  I don't know why, and I don't think it should be there.

Similarly `guides/mesos-marathon/centos/weave`

**Comment by errordeveloper** [comment]
It's the easiest way to push back on when each of the guides is updated.

**Comment by bboreham** [comment]
OK, thanks for the answer, but if you're going to take that approach then you have to do it consistently.  The `weave-and-docker-platform`, at least, has part 1 installing the latest release and part 2 (if you use the script) using a pinned version.
