### ISSUE TITLE
Automated testing

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/guides#94]
We must do it as soon as we can.

**Comment by errordeveloper** [comment]
I had a brief look at doctest, as it's something that works very nicely in the Python land.

```
> cat test.md 
# Hello!

~~~
>>> True or False
True
~~~
> python -m doctest test.md
```

However, it looks like we would need to look into the [implementing `DocTestParser`, `DocTestRunner` and `OutputChecker`](https://docs.python.org/2/library/doctest.html#advanced-api), if anyone is fancy.

**Comment by errordeveloper** [comment]
A more ad-hoc simplistic solution would involve hacking Jekyll setup in such a way that there would be some shared scripts (e.g. install weave, check status is what's expected) and page-specific bits inside the specific markdown file that could be captured and written to disc, then executed in and tested simply on the basis of the return codes.

**Comment by abuehrle** [comment]
Basically, the guides need to be reviewed.  I am not sure automated testing is going to solve this.  There could be errors in the tests themselves. 

And then you have two things to update: the tests and the guides.

**Comment by dpw** [comment]
> I had a brief look at doctest, as it's something that works very nicely in the Python land.

I have experience with extending doctest (to adjust how it checks whether the actual output matches the expected output).  As you say, it works well for python.  But it seemed very python-centric. That was several years ago though.  Have you seen any examples of people using it for non-python testing?

**Comment by errordeveloper** [comment]
> Have you seen any examples of people using it for non-python testing?

Haven't found anything yet...

**Comment by errordeveloper** [comment]
> Haven't found anything yet...

Here is slightly dated project, but probably worse taking a look: https://bitbucket.org/michilu/shell-doctest

**Comment by errordeveloper** [comment]
[A search](https://github.com/search?utf8=%E2%9C%93&q=shell+doctest) brings a [more recently updated fork](https://github.com/aohta/shell-doctest) as well as [another project written in Go](https://github.com/liquidz/shelltest).
